### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Omar-Cuenca** [LuisCarlosLarios/LuxoftPrueba#1]
Creo que se te olvido subir 2 archivos

![image](https://user-images.githubusercontent.com/98343802/201977728-41bedd3c-4bcf-4a15-bad5-763aec3d490c.png)

Recien clonado el archivo no lo puedo correr

**Comment by LuisCarlosLarios** [comment]
Voy a revisar ahora mismo y pongo cualquier instrucción en el readme. El programa debería abrir y si hay conexión con la api. Sin embargo hay un bug en el despliegue, y por lo tanto no se ven las películas. Para que hora puedo hacer el envío de estás correcciones?


________________________________
From: Omar Cuenca ***@***.***>
Sent: Tuesday, November 15, 2022 8:47 AM
To: LuisCarlosLarios/LuxoftPrueba ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LuisCarlosLarios/LuxoftPrueba] Missing Files (Issue #1)


Creo que se te olvido subir 2 archivos

[image]<https://user-images.githubusercontent.com/98343802/201977728-41bedd3c-4bcf-4a15-bad5-763aec3d490c.png>

Recien clonado el archivo no lo puedo correr

**Comment by Omar-Cuenca** [comment]
lo antes posible
aun puedo abrir un espacio para el miercoles y te revisamos
pero lo principal es que jale

**Comment by Omar-Cuenca** [comment]
El proyecto compila
